[package]
name = "vulkano_text"
version = "0.8.0"
authors = ["Rukai <rubickent@gmail.com>"]
description = "Render text with the DejaVu font using the Vulkano library."
license = "MIT"
repository = "https://github.com/rukai/vulkano-text"
keywords = ["vulkano", "text", "font"]

[dependencies]
rusttype = { version = "0.6", features = ["gpu_cache"] }
vulkano = "0.10"
vulkano-shader-derive = "0.10"

[dev-dependencies]
winit = "0.17"
vulkano-win = "0.10"
