[package]
name = "vulkano_text"
version = "0.6.1" # TODO: next release increment minor version, because the lifetimes on DrawText were removed
authors = ["Rukai <rubickent@gmail.com>"]
description = "Render text with the DejaVu font using the Vulkano library."
license = "MIT"
repository = "https://github.com/rukai/vulkano-text"
keywords = ["vulkano", "text", "font"]

[dependencies]
rusttype = { version = "0.6", features = ["gpu_cache"] }
# check the readme.md for more details on whats going on here
vulkano = { git = "https://github.com/rukai/vulkano", branch = "fix_cpu_pool_conflict_key" }
vulkano-shader-derive = { git = "https://github.com/rukai/vulkano", branch = "fix_cpu_pool_conflict_key" }

[dev-dependencies]
winit = { git = "https://github.com/tomaka/winit" }
vulkano-win = { git = "https://github.com/rukai/vulkano", branch = "git_winit" }
