[package]
name = "vulkano_text"
version = "0.7.0"
authors = ["Rukai <rubickent@gmail.com>"]
description = "Render text with the DejaVu font using the Vulkano library."
license = "MIT"
repository = "https://github.com/rukai/vulkano-text"
keywords = ["vulkano", "text", "font"]

[dependencies]
rusttype = "0.2"
# check the readme.md for more details on whats going on here
vulkano = "0.9"
vulkano-shader-derive = "0.9"

[dev-dependencies]
winit = "0.11"
vulkano-win = "0.9"
