[package]
name = "vulkano_text"
version = "0.9.0"
authors = ["Rukai <rubickent@gmail.com>"]
description = "Render text with the DejaVu font using the Vulkano library."
license = "MIT"
repository = "https://github.com/rukai/vulkano-text"
keywords = ["vulkano", "text", "font"]

[dependencies]
rusttype = { version = "0.7", features = ["gpu_cache"] }
vulkano = { git = "https://github.com/vulkano-rs/vulkano" }
vulkano-shaders = { git = "https://github.com/vulkano-rs/vulkano" }

[dev-dependencies]
winit = "0.17"
vulkano-win = { git = "https://github.com/vulkano-rs/vulkano" }
