[package]
name = "vulkano_text"
version = "0.6.1"
authors = ["Rukai <rubickent@gmail.com>"]
description = "Render text with the DejaVu font using the Vulkano library."
license = "MIT"
repository = "https://github.com/rukai/vulkano-text"
keywords = ["vulkano", "text", "font"]

[dependencies]
rusttype = "0.2"
# check the readme.md for more details on whats going on here
vulkano = { git = "https://github.com/vulkano-rs/vulkano" }
vulkano-shader-derive = { git = "https://github.com/vulkano-rs/vulkano" }

[dev-dependencies]
winit = { git = "https://github.com/tomaka/winit" }
vulkano-win = { git = "https://github.com/rukai/vulkano", branch = "git_winit" }
